# Generated by Django 2.1.7 on 2019-03-27 11:32

import basedata
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.CharField(db_column='id', default=basedata.get_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('test_id', models.CharField(db_column='test_id', editable=False, max_length=32)),
                ('state', models.CharField(db_column='state', max_length=100)),
                ('state_data', models.TextField(db_column='state_data', verbose_name='Json数据')),
            ],
            options={
                'verbose_name': 'csv_data',
                'verbose_name_plural': 'csv_data',
                'db_table': 'csv_data',
            },
        ),
        migrations.CreateModel(
            name='LocustTest',
            fields=[
                ('id', models.CharField(db_column='id', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('test_data', models.TextField(db_column='test_data', verbose_name='Json数据')),
            ],
            options={
                'verbose_name': 'locust_test',
                'verbose_name_plural': 'locust_test',
                'db_table': 'locust_test',
            },
        ),
        migrations.CreateModel(
            name='StatisticsData',
            fields=[
                ('id', models.CharField(db_column='id', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('data', models.TextField(db_column='data', verbose_name='Json数据')),
            ],
            options={
                'verbose_name': 'statistics_data',
                'verbose_name_plural': 'statistics_data',
                'db_table': 'statistics_data',
            },
        ),
    ]
