# Generated by Django 2.1.7 on 2019-04-02 10:29

import basedata
import basedata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressureTestMode',
            fields=[
                ('id', models.CharField(db_column='id', default=basedata.get_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('test_mode', models.CharField(db_column='test_mode', max_length=100, verbose_name='测试方式')),
                ('test_type', models.CharField(choices=[('api', 'api'), ('browser', 'browser')], db_column='test_type', max_length=100, verbose_name='类别')),
                ('import_path', models.CharField(db_column='import_path', max_length=100, unique=True, verbose_name='测试脚本引入路径')),
                ('script', models.FileField(db_column='script', unique=True, upload_to=basedata.models.upload_path, verbose_name='测试脚本文件')),
                ('describe', models.TextField(blank=True, db_column='describe', null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '压力测试方式',
                'verbose_name_plural': '压力测试方式',
                'db_table': 'pressure_test_mode',
            },
        ),
        migrations.CreateModel(
            name='RequestMethod',
            fields=[
                ('id', models.CharField(db_column='id', default=basedata.get_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('method', models.CharField(db_column='method', max_length=10, verbose_name='方法')),
                ('describe', models.TextField(blank=True, db_column='describe', null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '请求方法',
                'verbose_name_plural': '请求方法',
                'db_table': 'request_method',
            },
        ),
    ]
