# Generated by Django 2.1.7 on 2019-04-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressuretestmode',
            name='test_type',
            field=models.CharField(choices=[('api', 'api'), ('browser', 'browser'), ('disable', 'disable')], db_column='test_type', max_length=100, verbose_name='类别'),
        ),
    ]
