# Generated by Django 2.1.7 on 2019-04-02 10:29

import basedata
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroServiceApi',
            fields=[
                ('id', models.CharField(db_column='id', default=basedata.get_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('url', models.CharField(db_column='url', max_length=200, verbose_name='服务(url)')),
                ('service_source', models.CharField(db_column='service_source', max_length=100, verbose_name='服务来源')),
                ('params', models.TextField(blank=True, db_column='params', null=True, verbose_name='请求参数')),
                ('body', models.TextField(blank=True, db_column='body', null=True, verbose_name='请求体')),
                ('describe', models.TextField(blank=True, db_column='describe', null=True, verbose_name='描述')),
                ('request_method', models.ForeignKey(db_column='request_method', on_delete=django.db.models.deletion.PROTECT, to='basedata.RequestMethod', verbose_name='请求方法')),
            ],
            options={
                'verbose_name': '微服务接口明细',
                'verbose_name_plural': '微服务接口明细',
                'db_table': 'micro_service_api',
            },
        ),
    ]
